PROC=ldrdata

include ../plugin.mak

# MAKEDEP dependency list ------------------
$(F)ldrdata$(O) : $(I)bitrange.hpp $(I)bytes.hpp $(I)config.hpp             \
                  $(I)diff3.hpp $(I)diskio.hpp $(I)exehdr.h $(I)fixup.hpp   \
                  $(I)fpro.h $(I)funcs.hpp $(I)ida.hpp $(I)idp.hpp          \
                  $(I)ieee.h $(I)kernwin.hpp $(I)lines.hpp $(I)llong.hpp    \
                  $(I)loader.hpp $(I)merge.hpp $(I)mergemod.hpp             \
                  $(I)nalt.hpp $(I)netnode.hpp $(I)pro.h $(I)range.hpp      \
                  $(I)segment.hpp $(I)ua.hpp $(I)xref.hpp                   \
                  ../../ldr/aof/aof.h ../../ldr/elf/elf.h                   \
                  ../../ldr/elf/elfbase.h ../../ldr/pe/pe.h ldrdata.cpp
