PROC=pef

include ../loader.mak

# MAKEDEP dependency list ------------------
$(F)pef$(O)     : $(I)../ldr/coff/dbxstcla.h $(I)../ldr/coff/storclas.h     \
                  $(I)auto.hpp $(I)bitrange.hpp $(I)bytes.hpp               \
                  $(I)config.hpp $(I)diskio.hpp $(I)entry.hpp               \
                  $(I)fixup.hpp $(I)fpro.h $(I)funcs.hpp                    \
                  $(I)ida.hpp $(I)idp.hpp $(I)ieee.h $(I)kernwin.hpp        \
                  $(I)lines.hpp $(I)llong.hpp $(I)loader.hpp $(I)nalt.hpp   \
                  $(I)name.hpp $(I)netnode.hpp $(I)offset.hpp $(I)pro.h     \
                  $(I)range.hpp $(I)segment.hpp $(I)segregs.hpp             \
                  $(I)typeinf.hpp $(I)ua.hpp $(I)xref.hpp                   \
                  ../../module/ppc/notify_codes.hpp ../coff/syms.h          \
                  ../idaldr.h common.cpp pef.cpp pef.hpp
